server:
  port: 1234
spring:
  datasource:
    url: jdbc:mysql://database-1.cskxmd3bbixc.us-east-2.rds.amazonaws.com/project?useSSL=false&serverTimezone=UTC
    username: root
    password: pass$1234
  